// projects/montpc_crm/frontend/src/vue-components/dashboard/Dashboard.vue
<template>
  <div class="container mx-auto p-4">
    <div class="mb-8">
      <h1 class="text-3xl font-bold mb-2" data-testid="dashboard-title">Dashboard</h1>
      <p class="text-gray-600" data-testid="welcome-message">Welcome to MontPC CRM System</p>
    </div>

    <!-- Search Bar -->
    <div class="mb-8">
      <form @submit.prevent="handleSearch" class="flex" data-testid="search-form">
        <input
          type="text"
          v-model="searchQuery"
          placeholder="Search customers, tickets..."
          class="flex-grow p-2 border border-gray-300 rounded-l"
          data-testid="search-input"
        />
        <button
          type="submit"
          class="bg-blue-500 text-white px-4 py-2 rounded-r"
          data-testid="search-button"
        >
          Search
        </button>
      </form>
    </div>

    <!-- Quick Actions -->
    <div class="mb-8">
      <h2 class="text-xl font-semibold mb-4">Quick Actions</h2>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4" data-testid="quick-actions">
        <router-link
          to="/customers/new"
          class="bg-blue-100 hover:bg-blue-200 p-4 rounded text-center"
          @click="handleActionClick('new-customer')"
        >
          <div class="text-blue-800 font-medium">New Customer</div>
        </router-link>
        <router-link
          to="/tickets/new"
          class="bg-green-100 hover:bg-green-200 p-4 rounded text-center"
          @click="handleActionClick('new-ticket')"
          data-testid="action-create"
        >
          <div class="text-green-800 font-medium">New Repair Ticket</div>
        </router-link>
        <button
          class="bg-purple-100 hover:bg-purple-200 p-4 rounded text-center"
          @click="handleActionClick('sync-data')"
          data-testid="action-sync"
        >
          <div class="text-purple-800 font-medium">Sync Data</div>
        </button>
        <button
          class="bg-yellow-100 hover:bg-yellow-200 p-4 rounded text-center"
          @click="handleActionClick('reports')"
          data-testid="action-reports"
        >
          <div class="text-yellow-800 font-medium">Generate Reports</div>
        </button>
      </div>
    </div>

    <!-- Stats Overview -->
    <div v-if="loading" class="text-center p-4">
      Loading dashboard data...
    </div>
    <div v-else-if="error" class="text-center p-4 text-red-600">
      {{ error }}
    </div>
    <div v-else class="mb-8" data-testid="stats-section">
      <h2 class="text-xl font-semibold mb-4">Overview</h2>
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div class="bg-white p-4 rounded shadow" data-testid="stat-customers">
          <div class="text-gray-500">Total Customers</div>
          <div class="text-2xl font-bold">{{ stats.customerCount }}</div>
        </div>
        <div class="bg-white p-4 rounded shadow" data-testid="stat-tickets">
          <div class="text-gray-500">Total Tickets</div>
          <div class="text-2xl font-bold">{{ stats.ticketCount }}</div>
        </div>
        <div class="bg-white p-4 rounded shadow" data-testid="stat-pending">
          <div class="text-gray-500">Pending Tickets</div>
          <div class="text-2xl font-bold">{{ stats.pendingTickets }}</div>
        </div>
        <div class="bg-white p-4 rounded shadow" data-testid="stat-completed">
          <div class="text-gray-500">Completed Tickets</div>
          <div class="text-2xl font-bold">{{ stats.completedTickets }}</div>
        </div>
      </div>
    </div>

    <!-- Recent Activity -->
    <div class="mb-8" data-testid="recent-activity">
      <h2 class="text-xl font-semibold mb-4">Recent Activity</h2>
      <div class="bg-white p-4 rounded shadow">
        <div class="divide-y">
          <div v-for="(activity, index) in activities" :key="activity.id" class="py-2">
            <div class="text-sm text-gray-500">{{ activity.date }}</div>
            <div class="flex justify-between items-center">
              <div :data-testid="`activity-${activity.id}`">{{ activity.text }}</div>
              <div class="text-xs text-gray-500">{{ activity.time }}</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Quick Links -->
    <div>
      <h2 class="text-xl font-semibold mb-4">Quick Links</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <router-link
          to="/customers"
          class="bg-white p-4 rounded shadow hover:shadow-md"
        >
          <div class="font-medium">Customer Management</div>
          <div class="text-sm text-gray-500">View and manage all customers</div>
        </router-link>
        <router-link
          to="/tickets"
          class="bg-white p-4 rounded shadow hover:shadow-md"
        >
          <div class="font-medium">Repair Ticket Management</div>
          <div class="text-sm text-gray-500">View and manage all repair tickets</div>
        </router-link>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, reactive, onMounted } from 'vue';
import { customersService, ticketsService } from '../../api/services';

interface DashboardStats {
  customerCount: number;
  ticketCount: number;
  pendingTickets: number;
  completedTickets: number;
}

interface Activity {
  id: number;
  text: string;
  date: string;
  time: string;
}

export default defineComponent({
  name: 'Dashboard',
  props: {
    userName: {
      type: String,
      default: ''
    }
  },
  emits: ['search', 'action-select'],
  setup(props, { emit }) {
    // Reactive state
    const searchQuery = ref('');
    const stats = reactive<DashboardStats>({
      customerCount: 0,
      ticketCount: 0,
      pendingTickets: 0,
      completedTickets: 0
    });
    const loading = ref(true);
    const error = ref<string | null>(null);

    // Mock activities for now
    const activities = ref<Activity[]>([
      { id: 1, text: 'New customer added: John Doe', date: 'Today', time: '10:30 AM' },
      { id: 2, text: 'Ticket #1234 status changed to "In Progress"', date: 'Today', time: '9:15 AM' },
      { id: 3, text: 'New repair ticket created for Jane Smith', date: 'Yesterday', time: '4:45 PM' }
    ]);

    // Methods
    const fetchDashboardData = async () => {
      try {
        loading.value = true;
        
        // Fetch customers and tickets data
        const customersResponse = await customersService.getAll();
        const ticketsResponse = await ticketsService.getAll();
        
        // Handle both response formats (for backward compatibility)
        const customers = 'data' in customersResponse 
          ? customersResponse.data as any[]
          : 'items' in customersResponse
            ? customersResponse.items as any[]
            : [] as any[];
        const tickets = ticketsResponse || [] as any[];
        
        // Calculate dashboard stats
        const pendingTickets = Array.isArray(tickets) ? tickets.filter((ticket: any) =>
          ['PENDING', 'IN_PROGRESS', 'WAITING_FOR_PARTS'].includes(ticket.status)
        ).length : 0;
        
        const completedTickets = Array.isArray(tickets) ? tickets.filter((ticket: any) =>
          ticket.status === 'COMPLETED'
        ).length : 0;
        
        // Update reactive state
        stats.customerCount = customers.length;
        stats.ticketCount = Array.isArray(tickets) ? tickets.length : 0;
        stats.pendingTickets = pendingTickets;
        stats.completedTickets = completedTickets;
        
        error.value = null;
      } catch (err) {
        console.error('Error fetching dashboard data:', err);
        error.value = 'Failed to load dashboard data. Please try again later.';
        
        // Use demo data for local development or when API fails
        stats.customerCount = 2;
        stats.ticketCount = 4;
        stats.pendingTickets = 3;
        stats.completedTickets = 1;
      } finally {
        loading.value = false;
      }
    };

    const handleSearch = () => {
      emit('search', searchQuery.value);
    };

    const handleActionClick = (action: string) => {
      emit('action-select', action);
    };

    // Lifecycle hooks
    onMounted(() => {
      fetchDashboardData();
    });

    return {
      searchQuery,
      stats,
      loading,
      error,
      activities,
      handleSearch,
      handleActionClick
    };
  }
});
</script>

<style scoped>
/* Additional component-specific styles can be added here */
</style>

// projects/montpc_crm/src/components/dashboard/Dashboard.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { customersService, ticketsService } from '../../api/services';

// Types
interface DashboardProps {
  onSearch?: (query: string) => void;
  onActionSelect?: (action: string) => void;
}

interface DashboardStats {
  totalCustomers: number;
  totalTickets: number;
  pendingTickets: number;
  completedTickets: number;
}

// Recent activity mock data - in real app this would come from API
const recentActivities = [
  { id: 1, text: 'New customer added: John Doe', timestamp: new Date().toISOString() },
  { id: 2, text: 'Ticket #1234 status changed to "In Progress"', timestamp: new Date().toISOString() },
  { id: 3, text: 'New repair ticket created for Jane Smith', timestamp: new Date().toISOString() }
];

// Quick actions available on dashboard
const quickActions = [
  { id: 'new-customer', label: 'New Customer', icon: '👤' },
  { id: 'new-ticket', label: 'New Ticket', icon: '🎫' },
  { id: 'sync-data', label: 'Sync Data', icon: '🔄' },
  { id: 'reports', label: 'Reports', icon: '📊' }
];

const Dashboard: React.FC<DashboardProps> = ({ onSearch, onActionSelect }) => {
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [stats, setStats] = useState<DashboardStats>({
    totalCustomers: 0,
    totalTickets: 0,
    pendingTickets: 0,
    completedTickets: 0
  });
  const [searchQuery, setSearchQuery] = useState<string>('');

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        setLoading(true);
        setError(null);

        // Fetch customer data
        const customersResponse = await customersService.getAll();
        const customers = customersResponse.data || [];

        // Fetch ticket data
        const tickets = await ticketsService.getAll();

        // Calculate stats
        const completedTickets = tickets.filter((ticket: any) => ticket.status === 'COMPLETED');
        const pendingTickets = tickets.filter((ticket: any) => ticket.status !== 'COMPLETED');

        setStats({
          totalCustomers: customers.length,
          totalTickets: tickets.length,
          pendingTickets: pendingTickets.length,
          completedTickets: completedTickets.length
        });

        setLoading(false);
      } catch (err) {
        setError('Failed to load dashboard data. Please try again later.');
        setLoading(false);
        console.error('Dashboard data fetch error:', err);
      }
    };

    fetchDashboardData();
  }, []);

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (onSearch) {
      onSearch(searchQuery);
    }
  };

  const handleActionClick = (actionId: string) => {
    if (onActionSelect) {
      onActionSelect(actionId);
    }
  };

  if (error) {
    return (
      <div className="dashboard-error">
        <h1>Dashboard</h1>
        <div className="error-message">{error}</div>
        <button onClick={() => window.location.reload()}>Try Again</button>
      </div>
    );
  }

  return (
    <div className="dashboard-container">
      <header className="dashboard-header">
        <h1>Dashboard</h1>
        <p>Welcome to MontPC CRM System</p>
      </header>

      {loading ? (
        <div className="loading-indicator">Loading dashboard data...</div>
      ) : (
        <>
          {/* Search bar */}
          <div className="search-section">
            <form onSubmit={handleSearchSubmit}>
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search customers, tickets..."
              />
              <button type="submit">Search</button>
            </form>
          </div>

          {/* Quick Actions */}
          <div className="quick-actions-section">
            <h2>Quick Actions</h2>
            <div className="action-buttons">
              {quickActions.map(action => (
                <button
                  key={action.id}
                  onClick={() => handleActionClick(action.id)}
                  className="action-button"
                >
                  <span className="action-icon">{action.icon}</span>
                  <span>{action.label}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Stats Overview */}
          <div className="stats-section">
            <h2>Overview</h2>
            <div className="stats-grid">
              <div className="stat-card">
                <h3>Total Customers</h3>
                <div className="stat-value">{stats.totalCustomers}</div>
                <Link to="/customers">View all customers</Link>
              </div>
              <div className="stat-card">
                <h3>Total Tickets</h3>
                <div className="stat-value">{stats.totalTickets}</div>
                <Link to="/tickets">View all tickets</Link>
              </div>
              <div className="stat-card">
                <h3>Pending Tickets</h3>
                <div className="stat-value">{stats.pendingTickets}</div>
                <Link to="/tickets?status=pending">View pending</Link>
              </div>
              <div className="stat-card">
                <h3>Completed Tickets</h3>
                <div className="stat-value">{stats.completedTickets}</div>
                <Link to="/tickets?status=completed">View completed</Link>
              </div>
            </div>
          </div>

          {/* Recent Activity */}
          <div className="recent-activity-section">
            <h2>Recent Activity</h2>
            <ul className="activity-list">
              {recentActivities.map(activity => (
                <li key={activity.id} className="activity-item">
                  <div className="activity-text">{activity.text}</div>
                  <div className="activity-time">
                    {new Date(activity.timestamp).toLocaleTimeString()}
                  </div>
                </li>
              ))}
            </ul>
            <Link to="/activity" className="view-all-link">View all activity</Link>
          </div>
        </>
      )}
    </div>
  );
};

export default Dashboard;
