// packages/core/src/frontend/src/components/common/Input.tsx
import React from 'react';
import styled from 'styled-components';
import { Theme } from '../../../themes/defaultTheme';

interface InputProps {
  type?: string;
  placeholder?: string;
  value?: string;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
  disabled?: boolean;
  error?: boolean;
  errorMessage?: string;
  id?: string;
  name?: string;
  required?: boolean;
  className?: string;
  [key: string]: any; // For data-testid and other props
}

interface StyledInputProps {
  error: boolean;
  disabled: boolean;
  theme: Theme;
}

const StyledInputContainer = styled.div`
  display: flex;
  flex-direction: column;
  margin-bottom: ${props => props.theme.spacing.md};
  width: 100%;
`;

const StyledInput = styled.input<StyledInputProps>`
  font-family: ${props => props.theme.typography.fontFamily};
  font-size: ${props => props.theme.typography.fontSize.sm};
  padding: ${props => props.theme.spacing.sm} ${props => props.theme.spacing.md};
  border-radius: ${props => props.theme.borderRadius.input};
  border: 1px solid ${props => 
    props.error 
      ? props.theme.colors.error 
      : props.disabled 
        ? props.theme.colors.border.light 
        : props.theme.colors.border.medium
  };
  background-color: ${props => 
    props.disabled 
      ? props.theme.colors.background.paper 
      : props.theme.colors.background.default
  };
  color: ${props => 
    props.disabled 
      ? props.theme.colors.text.disabled 
      : props.theme.colors.text.primary
  };
  outline: none;
  transition: border-color ${props => props.theme.transitions.duration.short} ${props => props.theme.transitions.easing.easeInOut};
  
  &:focus {
    border-color: ${props => 
      props.error 
        ? props.theme.colors.error 
        : props.theme.colors.primary
    };
    box-shadow: 0 0 0 2px ${props => 
      props.error 
        ? `${props.theme.colors.error}33` 
        : `${props.theme.colors.primary}33`
    };
  }
  
  &::placeholder {
    color: ${props => props.theme.colors.text.hint};
  }
`;

const ErrorMessage = styled.span`
  color: ${props => props.theme.colors.error};
  font-size: ${props => props.theme.typography.fontSize.xs};
  margin-top: ${props => props.theme.spacing.xs};
`;

export const Input: React.FC<InputProps> = ({
  type = 'text',
  placeholder,
  value,
  onChange,
  disabled = false,
  error = false,
  errorMessage,
  id,
  name,
  required = false,
  className,
  ...rest
}) => {
  // Generate a unique ID if one wasn't provided
  const inputId = id || `input-${Math.random().toString(36).substr(2, 9)}`;
  
  // Generate error message ID if error message exists
  const errorId = error && errorMessage ? `${inputId}-error` : undefined;
  
  return (
    <StyledInputContainer>
      <StyledInput
        type={type}
        placeholder={placeholder}
        value={value}
        onChange={onChange}
        disabled={disabled}
        error={error}
        id={inputId}
        name={name}
        required={required}
        className={className}
        aria-invalid={error ? 'true' : 'false'}
        aria-describedby={errorId}
        aria-required={required ? 'true' : undefined}
        aria-disabled={disabled ? 'true' : undefined}
        {...rest}
      />
      {error && errorMessage && (
        <ErrorMessage id={errorId} role="alert">
          {errorMessage}
        </ErrorMessage>
      )}
    </StyledInputContainer>
  );
};

// packages/vue-components/src/components/ui/Input.vue
<template>
  <div class="input-wrapper" :class="wrapperClasses">
    <label v-if="label" :for="inputId" class="input-label">
      {{ label }}
      <span v-if="required" class="input-required">*</span>
    </label>
    <div class="input-container">
      <input
        :id="inputId"
        :type="type"
        :value="modelValue"
        :placeholder="placeholder"
        :disabled="disabled"
        :required="required"
        :autofocus="autofocus"
        :class="inputClasses"
        @input="handleInput"
        @blur="$emit('blur', $event)"
        @focus="$emit('focus', $event)"
      />
    </div>
    <div v-if="error" class="input-error">{{ error }}</div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, PropType } from 'vue';
import { InputProps, SizeVariant } from '@/types';
import { v4 as uuidv4 } from 'uuid';

export default defineComponent({
  name: 'Input',
  props: {
    modelValue: {
      type: [String, Number],
      required: true
    },
    label: {
      type: String,
      default: ''
    },
    placeholder: {
      type: String,
      default: ''
    },
    type: {
      type: String,
      default: 'text'
    },
    size: {
      type: String as PropType<SizeVariant>,
      default: 'medium',
      validator: (value: string) => {
        return ['small', 'medium', 'large'].includes(value);
      }
    },
    disabled: {
      type: Boolean,
      default: false
    },
    error: {
      type: String,
      default: ''
    },
    required: {
      type: Boolean,
      default: false
    },
    autofocus: {
      type: Boolean,
      default: false
    }
  },
  emits: {
    'update:modelValue': (value: string | number) => true,
    'blur': (event: FocusEvent) => true,
    'focus': (event: FocusEvent) => true
  },
  setup(props, { emit }) {
    const inputId = `input-${uuidv4()}`;
    
    const wrapperClasses = computed(() => {
      return {
        [`input-size-${props.size}`]: true,
        'has-error': !!props.error,
        'is-disabled': props.disabled
      }
    });
    
    const inputClasses = computed(() => {
      return {
        'input': true,
        [`input-${props.size}`]: true,
        'input-error': !!props.error,
        'input-disabled': props.disabled
      }
    });
    
    const handleInput = (event: Event) => {
      const target = event.target as HTMLInputElement;
      emit('update:modelValue', props.type === 'number' ? Number(target.value) : target.value);
    };
    
    return {
      inputId,
      wrapperClasses,
      inputClasses,
      handleInput
    };
  }
});
</script>

<style scoped>
.input-wrapper {
  display: flex;
  flex-direction: column;
  margin-bottom: 1rem;
}

.input-label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  font-size: 0.875rem;
}

.input-required {
  color: #dc3545;
  margin-left: 0.25rem;
}

.input-container {
  position: relative;
}

.input {
  display: block;
  width: 100%;
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: 0.25rem;
  transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}

.input:focus {
  color: #495057;
  background-color: #fff;
  border-color: #80bdff;
  outline: 0;
  box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
}

.input::placeholder {
  color: #6c757d;
  opacity: 1;
}

.input-disabled,
.input:disabled {
  background-color: #e9ecef;
  opacity: 1;
  cursor: not-allowed;
}

.input-error {
  color: #dc3545;
  font-size: 0.875em;
  margin-top: 0.5rem;
}

.has-error .input {
  border-color: #dc3545;
}

.has-error .input:focus {
  border-color: #dc3545;
  box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.25);
}

/* Size variants */
.input-size-small .input-label {
  font-size: 0.75rem;
}

.input-small {
  padding: 0.25rem 0.5rem;
  font-size: 0.875rem;
  line-height: 1.5;
  border-radius: 0.2rem;
}

.input-medium {
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
  line-height: 1.5;
  border-radius: 0.25rem;
}

.input-large {
  padding: 0.5rem 1rem;
  font-size: 1.25rem;
  line-height: 1.5;
  border-radius: 0.3rem;
}

.input-size-large .input-label {
  font-size: 1rem;
}
</style>
